// Dados das Zonas de Pesca (Portugal Continental)
export const ZONES = [
  // ZONAS PROIBIDAS (Vermelho)
  {
    id: "zf1",
    name: "Parque Natural do Litoral Norte",
    type: "forbidden",
    tabuaUrl: "/Portugal/Braga/Esposende/",
    coordinates: [
      [41.56, -8.83],
      [41.56, -8.80],
      [41.51, -8.80],
      [41.51, -8.83],
    ],
    description: "Zona de Proteção. Pesca restrita ou proibida em áreas específicas para preservação.",
  },
  {
    id: "zf_povoa_porto",
    name: "Porto de Pesca da Póvoa de Varzim",
    type: "forbidden",
    tabuaUrl: "/Portugal/Porto/Povoa-de-Varzim/",
    coordinates: [
      [41.380, -8.775],
      [41.380, -8.760],
      [41.370, -8.760],
      [41.370, -8.775],
    ],
    description: "Pesca totalmente proibida nos molhes, canal de navegação e interior da doca.",
  },
  {
    id: "zf_mindelo",
    name: "Reserva Ornitológica de Mindelo",
    type: "forbidden",
    tabuaUrl: "/Portugal/Porto/Vila-do-Conde/",
    coordinates: [
      [41.325, -8.745],
      [41.325, -8.730],
      [41.305, -8.730],
      [41.305, -8.745],
    ],
    description: "Paisagem Protegida Regional. Pesca lúdica estritamente interdita nas linhas de água abrangidas.",
  },
  {
    id: "zf_viladoconde",
    name: "Porto de Vila do Conde / Foz do Ave",
    type: "forbidden",
    tabuaUrl: "/Portugal/Porto/Vila-do-Conde/",
    coordinates: [
      [41.340, -8.755],
      [41.340, -8.740],
      [41.330, -8.740],
      [41.330, -8.755],
    ],
    description: "Interdita na barra, canal de navegação, estaleiros e cais portuários por razões de segurança.",
  },
  {
    id: "zf_leixoes",
    name: "Porto de Leixões (Matosinhos)",
    type: "forbidden",
    tabuaUrl: "/Portugal/Porto/Matosinhos/",
    coordinates: [
      [41.190, -8.715],
      [41.190, -8.695],
      [41.175, -8.695],
      [41.175, -8.715],
    ],
    description: "Pesca totalmente proibida no canal exterior, anteporto, docas e marina por razões de segurança marítima.",
  },
  {
    id: "zf2",
    name: "Reserva Natural das Berlengas",
    type: "forbidden",
    tabuaUrl: "/Portugal/Leiria/Peniche/",
    coordinates: [
      [39.42, -9.52],
      [39.42, -9.48],
      [39.4, -9.48],
      [39.4, -9.52],
    ],
    description: "Área marinha protegida. Pesca fortemente limitada e sujeita a licenças especiais.",
  },
  {
    id: "zf3",
    name: "Parque Marinho da Arrábida",
    type: "forbidden",
    tabuaUrl: "/Portugal/Setubal/Sesimbra/",
    coordinates: [
      [38.45, -9.05],
      [38.45, -8.95],
      [38.42, -8.95],
      [38.42, -9.05],
    ],
    description: "Zona de Proteção Total. Pesca estritamente proibida (Pedra do Leão, etc).",
  },
  {
    id: "zf4",
    name: "Ilhotes do Martinhal (Sagres)",
    type: "forbidden",
    tabuaUrl: "/Portugal/Faro/Sagres/",
    coordinates: [
      [37.025, -8.935],
      [37.025, -8.920],
      [37.010, -8.920],
      [37.010, -8.935],
    ],
    description: "Interdição total de pesca por razões de conservação da biodiversidade.",
  },
  {
    id: "zf5",
    name: "Ria Formosa (Proteção Total)",
    type: "forbidden",
    tabuaUrl: "/Portugal/Faro/Faro/",
    coordinates: [
      [37.00, -7.95],
      [37.00, -7.90],
      [36.97, -7.90],
      [36.97, -7.95],
    ],
    description: "Áreas de viveiros e interdição ambiental. Proibida a pesca lúdica.",
  },

  // ZONAS PERMITIDAS (Verde)
  {
    id: "zp1",
    name: "Molhes de Viana do Castelo",
    type: "allowed",
    tabuaUrl: "/Portugal/Viana-do-Castelo/Viana-do-Castelo/",
    coordinates: [
      [41.69, -8.845],
      [41.69, -8.830],
      [41.67, -8.830],
      [41.67, -8.845],
    ],
    description: "Excelente local para pesca apeada ao robalo e sargo.",
  },
  {
    id: "zp_agucadoura",
    name: "Praia da Aguçadoura / Estela",
    type: "allowed",
    tabuaUrl: "/Portugal/Porto/Povoa-de-Varzim/",
    coordinates: [
      [41.440, -8.790],
      [41.440, -8.775],
      [41.420, -8.775],
      [41.420, -8.790],
    ],
    description: "Extenso areal excelente para a prática de surfcasting (robalo, sargo).",
  },
  {
    id: "zp2",
    name: "Molhes da Ria de Aveiro",
    type: "allowed",
    tabuaUrl: "/Portugal/Aveiro/Aveiro/",
    coordinates: [
      [40.645, -8.760],
      [40.645, -8.740],
      [40.635, -8.740],
      [40.635, -8.760],
    ],
    description: "Zona popular de pesca costeira. Bom para douradas e robalos.",
  },
  {
    id: "zp3",
    name: "Costa de Peniche",
    type: "allowed",
    tabuaUrl: "/Portugal/Leiria/Peniche/",
    coordinates: [
      [39.38, -9.42],
      [39.38, -9.35],
      [39.3, -9.35],
      [39.3, -9.42],
    ],
    description: "Zona fora da área de proteção, ideal para pesca desportiva embarcada e apeada.",
  },
  {
    id: "zp4",
    name: "Cabo Espichel",
    type: "allowed",
    tabuaUrl: "/Portugal/Setubal/Sesimbra/",
    coordinates: [
      [38.42, -9.23],
      [38.42, -9.20],
      [38.40, -9.20],
      [38.40, -9.23],
    ],
    description: "Pesqueiro icónico em falésia, exigente mas com grande potencial para peixe graúdo.",
  },
  {
    id: "zp5",
    name: "Costa Vicentina (Amoreira)",
    type: "allowed",
    tabuaUrl: "/Portugal/Faro/Sagres/",
    coordinates: [
      [37.36, -8.86],
      [37.36, -8.84],
      [37.32, -8.84],
      [37.32, -8.86],
    ],
    description: "Zona permitida de grande beleza natural, muito procurada para surfcasting.",
  },
  {
    id: "zp6",
    name: "Ponta da Piedade (Lagos)",
    type: "allowed",
    tabuaUrl: "/Portugal/Faro/Lagos/",
    coordinates: [
      [37.09, -8.68],
      [37.09, -8.66],
      [37.07, -8.66],
      [37.07, -8.68],
    ],
    description: "Zona mista de pedra e areia. Excelente para pesca embarcada costeira e spinning.",
  },
];
